import type { AppRole } from "@workspace/backend/permissions"

export const ROLES = [
  ["voyageur", "Voyageur"],
  ["vendeur_guichet", "Vendeur guichet"],
  ["vendeur_agence", "Vendeur agence"],
  ["taxateur", "Taxateur"],
  ["controleur_train", "Contrôleur train"],
  ["controleur_recettes", "Contrôleur recettes"],
  ["chef_gare", "Chef de gare"],
  ["comptable", "Comptable"],
  ["responsable_kpi", "Responsable KPI"],
  ["admin_fonctionnel", "Administrateur fonctionnel"],
  ["admin_it", "Administrateur technique"],
  ["direction_generale", "Direction générale"],
  ["audit_risques", "Audit et risques"],
  ["juriste", "Juriste"],
  ["regulateur_cotraf", "Régulateur COTRAF"],
  ["conducteur_ligne", "Conducteur de ligne"],
  ["visiteur_rames", "Visiteur de rames"],
  ["responsable_atelier", "Responsable d’atelier"],
  ["magasinier", "Magasinier"],
  ["agent_voie", "Agent de voie"],
  ["responsable_prn", "Responsable PRN"],
  ["technicien_signalisation", "Technicien signalisation"],
  ["gestionnaire_fret", "Gestionnaire fret"],
  ["fiscaliste_tresorier", "Fiscaliste / trésorier"],
  ["gestionnaire_paie", "Gestionnaire de paie"],
  ["planificateur_roulements", "Planificateur des roulements"],
  ["medecin_travail", "Médecin du travail"],
  ["inspecteur_securite", "Inspecteur sécurité"],
  ["chef_train", "Chef de train"],
  ["ingenieur_atelier", "Ingénieur d’atelier"],
  ["contremaitre_atelier", "Contremaître d’atelier"],
  ["gestionnaire_stocks", "Gestionnaire de stocks"],
  ["cantonnier", "Cantonnier"],
  ["agent_ouvrages_ponts", "Responsable ouvrages d’art & ponts"],
  ["technicien_telecoms", "Technicien télécoms"],
  ["chef_vente", "Chef de vente"],
  ["gestionnaire_litiges_fret", "Gestionnaire des litiges fret"],
  ["comptable_auxiliaire", "Comptable auxiliaire"],
  ["fiscaliste", "Fiscaliste"],
  ["tresorier", "Trésorier"],
  ["infirmier_travail", "Infirmier du travail"],
  ["enqueteur_accidents", "Enquêteur accidents ferroviaires"],
  ["responsable_environnement", "Responsable environnement & Lopé"],
  ["representant_comilog", "Représentant COMILOG"],
  ["representant_meridiam", "Représentant Meridiam"],
  ["representant_etat", "Représentant de l’État gabonais"],
  ["auditeur_artf", "Auditeur ARTF"],
  ["controleur_eaux_forets", "Contrôleur des Eaux et Forêts"],
  ["agent_douanes", "Agent des douanes"],
  ["operateur_gsez", "Opérateur GSEZ"],
  ["agent_dgi", "Agent DGI"],
  ["organisme_social", "Organisme social (CNSS / CNAMGS)"],
  ["bailleur_fonds", "Bailleur de fonds"],
] as const satisfies readonly (readonly [AppRole, string])[]

export const ROLE_LABELS = Object.fromEntries(ROLES) as Record<AppRole, string>
