/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as ai_chat from "../ai/chat.js";
import type * as ai_contracts from "../ai/contracts.js";
import type * as ai_conversations from "../ai/conversations.js";
import type * as ai_flux from "../ai/flux.js";
import type * as ai_memory from "../ai/memory.js";
import type * as ai_providers from "../ai/providers.js";
import type * as ai_rateLimiter from "../ai/rateLimiter.js";
import type * as ai_realtime from "../ai/realtime.js";
import type * as ai_rejeu from "../ai/rejeu.js";
import type * as ai_tools from "../ai/tools.js";
import type * as betterAuth_auth from "../betterAuth/auth.js";
import type * as betterAuth_effacement from "../betterAuth/effacement.js";
import type * as betterAuth_origins from "../betterAuth/origins.js";
import type * as crons from "../crons.js";
import type * as functions_accounting from "../functions/accounting.js";
import type * as functions_administration from "../functions/administration.js";
import type * as functions_ancillaries from "../functions/ancillaries.js";
import type * as functions_auditTrail from "../functions/auditTrail.js";
import type * as functions_bookings from "../functions/bookings.js";
import type * as functions_booklets from "../functions/booklets.js";
import type * as functions_cash from "../functions/cash.js";
import type * as functions_control from "../functions/control.js";
import type * as functions_customers from "../functions/customers.js";
import type * as functions_demoAccounts from "../functions/demoAccounts.js";
import type * as functions_devAuth from "../functions/devAuth.js";
import type * as functions_documents from "../functions/documents.js";
import type * as functions_fareSchedules from "../functions/fareSchedules.js";
import type * as functions_guichet from "../functions/guichet.js";
import type * as functions_management from "../functions/management.js";
import type * as functions_manualSales from "../functions/manualSales.js";
import type * as functions_monitoring from "../functions/monitoring.js";
import type * as functions_notificationCenter from "../functions/notificationCenter.js";
import type * as functions_notificationLog from "../functions/notificationLog.js";
import type * as functions_notifications from "../functions/notifications.js";
import type * as functions_pilotage from "../functions/pilotage.js";
import type * as functions_preferences from "../functions/preferences.js";
import type * as functions_referential from "../functions/referential.js";
import type * as functions_referentiels from "../functions/referentiels.js";
import type * as functions_reportSchedules from "../functions/reportSchedules.js";
import type * as functions_reporting from "../functions/reporting.js";
import type * as functions_rollup from "../functions/rollup.js";
import type * as functions_sales from "../functions/sales.js";
import type * as functions_trips from "../functions/trips.js";
import type * as functions_wallet from "../functions/wallet.js";
import type * as http from "../http.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_aztecRender from "../lib/aztecRender.js";
import type * as lib_courriels from "../lib/courriels.js";
import type * as lib_horaires from "../lib/horaires.js";
import type * as lib_libellesBillet from "../lib/libellesBillet.js";
import type * as lib_pdfMarque from "../lib/pdfMarque.js";
import type * as lib_polices from "../lib/polices.js";
import type * as lib_policesDonnees from "../lib/policesDonnees.js";
import type * as lib_reglement from "../lib/reglement.js";
import type * as lib_resend from "../lib/resend.js";
import type * as lib_saleContext from "../lib/saleContext.js";
import type * as lib_signature from "../lib/signature.js";
import type * as lib_ticketPdf from "../lib/ticketPdf.js";
import type * as lib_tripQuote from "../lib/tripQuote.js";
import type * as lib_walletImages from "../lib/walletImages.js";
import type * as lib_walletPass from "../lib/walletPass.js";
import type * as messaging_contracts from "../messaging/contracts.js";
import type * as messaging_core from "../messaging/core.js";
import type * as messaging_dispatch from "../messaging/dispatch.js";
import type * as messaging_linking from "../messaging/linking.js";
import type * as messaging_orchestrator from "../messaging/orchestrator.js";
import type * as messaging_telegram from "../messaging/telegram.js";
import type * as model_accounting from "../model/accounting.js";
import type * as model_ancillary from "../model/ancillary.js";
import type * as model_approval from "../model/approval.js";
import type * as model_aztec from "../model/aztec.js";
import type * as model_barcode from "../model/barcode.js";
import type * as model_caisse from "../model/caisse.js";
import type * as model_calendar from "../model/calendar.js";
import type * as model_cgv from "../model/cgv.js";
import type * as model_controlSummary from "../model/controlSummary.js";
import type * as model_demoPersonas from "../model/demoPersonas.js";
import type * as model_fares from "../model/fares.js";
import type * as model_inventory from "../model/inventory.js";
import type * as model_kpi from "../model/kpi.js";
import type * as model_memoire from "../model/memoire.js";
import type * as model_network from "../model/network.js";
import type * as model_permissions from "../model/permissions.js";
import type * as model_pricing from "../model/pricing.js";
import type * as model_sales from "../model/sales.js";
import type * as model_seating from "../model/seating.js";
import type * as model_supervision from "../model/supervision.js";
import type * as model_telephone from "../model/telephone.js";
import type * as model_titulaire from "../model/titulaire.js";
import type * as modules_continuity_model from "../modules/continuity/model.js";
import type * as modules_continuity_mutations from "../modules/continuity/mutations.js";
import type * as modules_continuity_queries from "../modules/continuity/queries.js";
import type * as modules_continuity_tables from "../modules/continuity/tables.js";
import type * as modules_copilot_agent from "../modules/copilot/agent.js";
import type * as modules_copilot_chat from "../modules/copilot/chat.js";
import type * as modules_copilot_conversations from "../modules/copilot/conversations.js";
import type * as modules_copilot_lecture from "../modules/copilot/lecture.js";
import type * as modules_copilot_model from "../modules/copilot/model.js";
import type * as modules_copilot_seed from "../modules/copilot/seed.js";
import type * as modules_copilot_tables from "../modules/copilot/tables.js";
import type * as modules_cotraf_model from "../modules/cotraf/model.js";
import type * as modules_cotraf_permissions from "../modules/cotraf/permissions.js";
import type * as modules_cotraf_queries from "../modules/cotraf/queries.js";
import type * as modules_cotraf_tables from "../modules/cotraf/tables.js";
import type * as modules_etudes_corpus from "../modules/etudes/corpus.js";
import type * as modules_etudes_ecriture from "../modules/etudes/ecriture.js";
import type * as modules_etudes_model from "../modules/etudes/model.js";
import type * as modules_etudes_mutations from "../modules/etudes/mutations.js";
import type * as modules_etudes_outils from "../modules/etudes/outils.js";
import type * as modules_etudes_queries from "../modules/etudes/queries.js";
import type * as modules_etudes_seed from "../modules/etudes/seed.js";
import type * as modules_etudes_tables from "../modules/etudes/tables.js";
import type * as modules_finance_model from "../modules/finance/model.js";
import type * as modules_finance_mutations from "../modules/finance/mutations.js";
import type * as modules_finance_queries from "../modules/finance/queries.js";
import type * as modules_finance_tables from "../modules/finance/tables.js";
import type * as modules_fret_manifest from "../modules/fret/manifest.js";
import type * as modules_fret_model from "../modules/fret/model.js";
import type * as modules_fret_permissions from "../modules/fret/permissions.js";
import type * as modules_fret_queries from "../modules/fret/queries.js";
import type * as modules_fret_tables from "../modules/fret/tables.js";
import type * as modules_ged_acces from "../modules/ged/acces.js";
import type * as modules_ged_model from "../modules/ged/model.js";
import type * as modules_ged_mutations from "../modules/ged/mutations.js";
import type * as modules_ged_pdf from "../modules/ged/pdf.js";
import type * as modules_ged_queries from "../modules/ged/queries.js";
import type * as modules_ged_seed from "../modules/ged/seed.js";
import type * as modules_ged_seedDonnees from "../modules/ged/seedDonnees.js";
import type * as modules_ged_tables from "../modules/ged/tables.js";
import type * as modules_gmao_acces from "../modules/gmao/acces.js";
import type * as modules_gmao_model from "../modules/gmao/model.js";
import type * as modules_gmao_mutations from "../modules/gmao/mutations.js";
import type * as modules_gmao_queries from "../modules/gmao/queries.js";
import type * as modules_gmao_seed from "../modules/gmao/seed.js";
import type * as modules_gmao_tables from "../modules/gmao/tables.js";
import type * as modules_infrastructure_acces from "../modules/infrastructure/acces.js";
import type * as modules_infrastructure_model from "../modules/infrastructure/model.js";
import type * as modules_infrastructure_mutations from "../modules/infrastructure/mutations.js";
import type * as modules_infrastructure_presentation from "../modules/infrastructure/presentation.js";
import type * as modules_infrastructure_queries from "../modules/infrastructure/queries.js";
import type * as modules_infrastructure_seed from "../modules/infrastructure/seed.js";
import type * as modules_infrastructure_tables from "../modules/infrastructure/tables.js";
import type * as modules_platform_approvalModel from "../modules/platform/approvalModel.js";
import type * as modules_platform_approvals from "../modules/platform/approvals.js";
import type * as modules_platform_audit from "../modules/platform/audit.js";
import type * as modules_platform_catalog from "../modules/platform/catalog.js";
import type * as modules_platform_documentModel from "../modules/platform/documentModel.js";
import type * as modules_platform_documents from "../modules/platform/documents.js";
import type * as modules_platform_environment from "../modules/platform/environment.js";
import type * as modules_platform_integration from "../modules/platform/integration.js";
import type * as modules_platform_integrationModel from "../modules/platform/integrationModel.js";
import type * as modules_platform_model from "../modules/platform/model.js";
import type * as modules_platform_mutations from "../modules/platform/mutations.js";
import type * as modules_platform_queries from "../modules/platform/queries.js";
import type * as modules_platform_tables from "../modules/platform/tables.js";
import type * as modules_platform_validators from "../modules/platform/validators.js";
import type * as modules_rh_acces from "../modules/rh/acces.js";
import type * as modules_rh_accueil from "../modules/rh/accueil.js";
import type * as modules_rh_agents from "../modules/rh/agents.js";
import type * as modules_rh_aptitude from "../modules/rh/aptitude.js";
import type * as modules_rh_conges from "../modules/rh/conges.js";
import type * as modules_rh_lecture from "../modules/rh/lecture.js";
import type * as modules_rh_model from "../modules/rh/model.js";
import type * as modules_rh_modelPaie from "../modules/rh/modelPaie.js";
import type * as modules_rh_paie from "../modules/rh/paie.js";
import type * as modules_rh_roulements from "../modules/rh/roulements.js";
import type * as modules_rh_seed from "../modules/rh/seed.js";
import type * as modules_rh_tables from "../modules/rh/tables.js";
import type * as modules_securite_acces from "../modules/securite/acces.js";
import type * as modules_securite_accueil from "../modules/securite/accueil.js";
import type * as modules_securite_actions from "../modules/securite/actions.js";
import type * as modules_securite_artf from "../modules/securite/artf.js";
import type * as modules_securite_enquetes from "../modules/securite/enquetes.js";
import type * as modules_securite_evenements from "../modules/securite/evenements.js";
import type * as modules_securite_inspections from "../modules/securite/inspections.js";
import type * as modules_securite_model from "../modules/securite/model.js";
import type * as modules_securite_seed from "../modules/securite/seed.js";
import type * as modules_securite_tables from "../modules/securite/tables.js";
import type * as seeds_controlDemo from "../seeds/controlDemo.js";
import type * as seeds_cotrafDemo from "../seeds/cotrafDemo.js";
import type * as seeds_demo from "../seeds/demo.js";
import type * as seeds_demoAccounts from "../seeds/demoAccounts.js";
import type * as seeds_demoActivite from "../seeds/demoActivite.js";
import type * as seeds_demoActiviteEcriture from "../seeds/demoActiviteEcriture.js";
import type * as seeds_demoActivitePlan from "../seeds/demoActivitePlan.js";
import type * as seeds_demoActiviteReset from "../seeds/demoActiviteReset.js";
import type * as seeds_enterpriseDemo from "../seeds/enterpriseDemo.js";
import type * as seeds_fretDemo from "../seeds/fretDemo.js";
import type * as seeds_history from "../seeds/history.js";
import type * as seeds_provisionalFares from "../seeds/provisionalFares.js";
import type * as seeds_referential from "../seeds/referential.js";
import type * as seeds_staffAccounts from "../seeds/staffAccounts.js";
import type * as testing from "../testing.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "ai/chat": typeof ai_chat;
  "ai/contracts": typeof ai_contracts;
  "ai/conversations": typeof ai_conversations;
  "ai/flux": typeof ai_flux;
  "ai/memory": typeof ai_memory;
  "ai/providers": typeof ai_providers;
  "ai/rateLimiter": typeof ai_rateLimiter;
  "ai/realtime": typeof ai_realtime;
  "ai/rejeu": typeof ai_rejeu;
  "ai/tools": typeof ai_tools;
  "betterAuth/auth": typeof betterAuth_auth;
  "betterAuth/effacement": typeof betterAuth_effacement;
  "betterAuth/origins": typeof betterAuth_origins;
  crons: typeof crons;
  "functions/accounting": typeof functions_accounting;
  "functions/administration": typeof functions_administration;
  "functions/ancillaries": typeof functions_ancillaries;
  "functions/auditTrail": typeof functions_auditTrail;
  "functions/bookings": typeof functions_bookings;
  "functions/booklets": typeof functions_booklets;
  "functions/cash": typeof functions_cash;
  "functions/control": typeof functions_control;
  "functions/customers": typeof functions_customers;
  "functions/demoAccounts": typeof functions_demoAccounts;
  "functions/devAuth": typeof functions_devAuth;
  "functions/documents": typeof functions_documents;
  "functions/fareSchedules": typeof functions_fareSchedules;
  "functions/guichet": typeof functions_guichet;
  "functions/management": typeof functions_management;
  "functions/manualSales": typeof functions_manualSales;
  "functions/monitoring": typeof functions_monitoring;
  "functions/notificationCenter": typeof functions_notificationCenter;
  "functions/notificationLog": typeof functions_notificationLog;
  "functions/notifications": typeof functions_notifications;
  "functions/pilotage": typeof functions_pilotage;
  "functions/preferences": typeof functions_preferences;
  "functions/referential": typeof functions_referential;
  "functions/referentiels": typeof functions_referentiels;
  "functions/reportSchedules": typeof functions_reportSchedules;
  "functions/reporting": typeof functions_reporting;
  "functions/rollup": typeof functions_rollup;
  "functions/sales": typeof functions_sales;
  "functions/trips": typeof functions_trips;
  "functions/wallet": typeof functions_wallet;
  http: typeof http;
  "lib/auth": typeof lib_auth;
  "lib/aztecRender": typeof lib_aztecRender;
  "lib/courriels": typeof lib_courriels;
  "lib/horaires": typeof lib_horaires;
  "lib/libellesBillet": typeof lib_libellesBillet;
  "lib/pdfMarque": typeof lib_pdfMarque;
  "lib/polices": typeof lib_polices;
  "lib/policesDonnees": typeof lib_policesDonnees;
  "lib/reglement": typeof lib_reglement;
  "lib/resend": typeof lib_resend;
  "lib/saleContext": typeof lib_saleContext;
  "lib/signature": typeof lib_signature;
  "lib/ticketPdf": typeof lib_ticketPdf;
  "lib/tripQuote": typeof lib_tripQuote;
  "lib/walletImages": typeof lib_walletImages;
  "lib/walletPass": typeof lib_walletPass;
  "messaging/contracts": typeof messaging_contracts;
  "messaging/core": typeof messaging_core;
  "messaging/dispatch": typeof messaging_dispatch;
  "messaging/linking": typeof messaging_linking;
  "messaging/orchestrator": typeof messaging_orchestrator;
  "messaging/telegram": typeof messaging_telegram;
  "model/accounting": typeof model_accounting;
  "model/ancillary": typeof model_ancillary;
  "model/approval": typeof model_approval;
  "model/aztec": typeof model_aztec;
  "model/barcode": typeof model_barcode;
  "model/caisse": typeof model_caisse;
  "model/calendar": typeof model_calendar;
  "model/cgv": typeof model_cgv;
  "model/controlSummary": typeof model_controlSummary;
  "model/demoPersonas": typeof model_demoPersonas;
  "model/fares": typeof model_fares;
  "model/inventory": typeof model_inventory;
  "model/kpi": typeof model_kpi;
  "model/memoire": typeof model_memoire;
  "model/network": typeof model_network;
  "model/permissions": typeof model_permissions;
  "model/pricing": typeof model_pricing;
  "model/sales": typeof model_sales;
  "model/seating": typeof model_seating;
  "model/supervision": typeof model_supervision;
  "model/telephone": typeof model_telephone;
  "model/titulaire": typeof model_titulaire;
  "modules/continuity/model": typeof modules_continuity_model;
  "modules/continuity/mutations": typeof modules_continuity_mutations;
  "modules/continuity/queries": typeof modules_continuity_queries;
  "modules/continuity/tables": typeof modules_continuity_tables;
  "modules/copilot/agent": typeof modules_copilot_agent;
  "modules/copilot/chat": typeof modules_copilot_chat;
  "modules/copilot/conversations": typeof modules_copilot_conversations;
  "modules/copilot/lecture": typeof modules_copilot_lecture;
  "modules/copilot/model": typeof modules_copilot_model;
  "modules/copilot/seed": typeof modules_copilot_seed;
  "modules/copilot/tables": typeof modules_copilot_tables;
  "modules/cotraf/model": typeof modules_cotraf_model;
  "modules/cotraf/permissions": typeof modules_cotraf_permissions;
  "modules/cotraf/queries": typeof modules_cotraf_queries;
  "modules/cotraf/tables": typeof modules_cotraf_tables;
  "modules/etudes/corpus": typeof modules_etudes_corpus;
  "modules/etudes/ecriture": typeof modules_etudes_ecriture;
  "modules/etudes/model": typeof modules_etudes_model;
  "modules/etudes/mutations": typeof modules_etudes_mutations;
  "modules/etudes/outils": typeof modules_etudes_outils;
  "modules/etudes/queries": typeof modules_etudes_queries;
  "modules/etudes/seed": typeof modules_etudes_seed;
  "modules/etudes/tables": typeof modules_etudes_tables;
  "modules/finance/model": typeof modules_finance_model;
  "modules/finance/mutations": typeof modules_finance_mutations;
  "modules/finance/queries": typeof modules_finance_queries;
  "modules/finance/tables": typeof modules_finance_tables;
  "modules/fret/manifest": typeof modules_fret_manifest;
  "modules/fret/model": typeof modules_fret_model;
  "modules/fret/permissions": typeof modules_fret_permissions;
  "modules/fret/queries": typeof modules_fret_queries;
  "modules/fret/tables": typeof modules_fret_tables;
  "modules/ged/acces": typeof modules_ged_acces;
  "modules/ged/model": typeof modules_ged_model;
  "modules/ged/mutations": typeof modules_ged_mutations;
  "modules/ged/pdf": typeof modules_ged_pdf;
  "modules/ged/queries": typeof modules_ged_queries;
  "modules/ged/seed": typeof modules_ged_seed;
  "modules/ged/seedDonnees": typeof modules_ged_seedDonnees;
  "modules/ged/tables": typeof modules_ged_tables;
  "modules/gmao/acces": typeof modules_gmao_acces;
  "modules/gmao/model": typeof modules_gmao_model;
  "modules/gmao/mutations": typeof modules_gmao_mutations;
  "modules/gmao/queries": typeof modules_gmao_queries;
  "modules/gmao/seed": typeof modules_gmao_seed;
  "modules/gmao/tables": typeof modules_gmao_tables;
  "modules/infrastructure/acces": typeof modules_infrastructure_acces;
  "modules/infrastructure/model": typeof modules_infrastructure_model;
  "modules/infrastructure/mutations": typeof modules_infrastructure_mutations;
  "modules/infrastructure/presentation": typeof modules_infrastructure_presentation;
  "modules/infrastructure/queries": typeof modules_infrastructure_queries;
  "modules/infrastructure/seed": typeof modules_infrastructure_seed;
  "modules/infrastructure/tables": typeof modules_infrastructure_tables;
  "modules/platform/approvalModel": typeof modules_platform_approvalModel;
  "modules/platform/approvals": typeof modules_platform_approvals;
  "modules/platform/audit": typeof modules_platform_audit;
  "modules/platform/catalog": typeof modules_platform_catalog;
  "modules/platform/documentModel": typeof modules_platform_documentModel;
  "modules/platform/documents": typeof modules_platform_documents;
  "modules/platform/environment": typeof modules_platform_environment;
  "modules/platform/integration": typeof modules_platform_integration;
  "modules/platform/integrationModel": typeof modules_platform_integrationModel;
  "modules/platform/model": typeof modules_platform_model;
  "modules/platform/mutations": typeof modules_platform_mutations;
  "modules/platform/queries": typeof modules_platform_queries;
  "modules/platform/tables": typeof modules_platform_tables;
  "modules/platform/validators": typeof modules_platform_validators;
  "modules/rh/acces": typeof modules_rh_acces;
  "modules/rh/accueil": typeof modules_rh_accueil;
  "modules/rh/agents": typeof modules_rh_agents;
  "modules/rh/aptitude": typeof modules_rh_aptitude;
  "modules/rh/conges": typeof modules_rh_conges;
  "modules/rh/lecture": typeof modules_rh_lecture;
  "modules/rh/model": typeof modules_rh_model;
  "modules/rh/modelPaie": typeof modules_rh_modelPaie;
  "modules/rh/paie": typeof modules_rh_paie;
  "modules/rh/roulements": typeof modules_rh_roulements;
  "modules/rh/seed": typeof modules_rh_seed;
  "modules/rh/tables": typeof modules_rh_tables;
  "modules/securite/acces": typeof modules_securite_acces;
  "modules/securite/accueil": typeof modules_securite_accueil;
  "modules/securite/actions": typeof modules_securite_actions;
  "modules/securite/artf": typeof modules_securite_artf;
  "modules/securite/enquetes": typeof modules_securite_enquetes;
  "modules/securite/evenements": typeof modules_securite_evenements;
  "modules/securite/inspections": typeof modules_securite_inspections;
  "modules/securite/model": typeof modules_securite_model;
  "modules/securite/seed": typeof modules_securite_seed;
  "modules/securite/tables": typeof modules_securite_tables;
  "seeds/controlDemo": typeof seeds_controlDemo;
  "seeds/cotrafDemo": typeof seeds_cotrafDemo;
  "seeds/demo": typeof seeds_demo;
  "seeds/demoAccounts": typeof seeds_demoAccounts;
  "seeds/demoActivite": typeof seeds_demoActivite;
  "seeds/demoActiviteEcriture": typeof seeds_demoActiviteEcriture;
  "seeds/demoActivitePlan": typeof seeds_demoActivitePlan;
  "seeds/demoActiviteReset": typeof seeds_demoActiviteReset;
  "seeds/enterpriseDemo": typeof seeds_enterpriseDemo;
  "seeds/fretDemo": typeof seeds_fretDemo;
  "seeds/history": typeof seeds_history;
  "seeds/provisionalFares": typeof seeds_provisionalFares;
  "seeds/referential": typeof seeds_referential;
  "seeds/staffAccounts": typeof seeds_staffAccounts;
  testing: typeof testing;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
  salesByDay: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"salesByDay">;
  salesByPointOfSale: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"salesByPointOfSale">;
  ticketsByTrip: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"ticketsByTrip">;
  revenueByTrip: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"revenueByTrip">;
};
